/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorsmart;

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class HasilForm extends javax.swing.JFrame {

    /**
     * Creates new form HasilFormm
     */
    Object hasilRangking[][];
     public HasilForm(Object hasilRangking[][]) {
        initComponents();
        this.hasilRangking = hasilRangking;
    }
     
     public void rangking(Object obj[][]){
        Object columns[] = {"Alternatif","Total","Rangking"};
        Object data[][] = new Object[obj.length][3];
        Object dataTemp[][] = new Object[obj.length][3];
        double hasil;
        for (int i = 0; i < obj.length; i++) {
            data[i][0] = obj[i][0];
            dataTemp[i][0] = obj[i][0];
            hasil=0;
            for (int j = 1; j < obj[0].length; j++) {
                hasil += Double.parseDouble(String.valueOf(obj[i][j]));
            }
            data[i][1] = hasil;
            dataTemp[i][1] = hasil;
        }
        
        int ranking = 1;
        double temp = 0;
        for(int i =0; i<dataTemp.length ; i++){
            int index = 0;
            for(int j = 0 ; j<dataTemp.length ; j++){
                if(temp < Double.parseDouble(String.valueOf(dataTemp[j][1]))) {
                    index = j;
                    temp = Double.parseDouble(String.valueOf(dataTemp[j][1]));
                }
            }
            dataTemp[index][1] = 0;
            data[index][2] = ranking;
            temp = 0;
            ranking++;
        }
        

        DefaultTableModel model = new DefaultTableModel(data, columns);
        tbl_hasil.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hasil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_hasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_hasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_hasil;
    // End of variables declaration//GEN-END:variables
}
