/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorsmart;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author genad
 */
public class HitungAlternatif extends javax.swing.JFrame {
    Object listKriteria[][];
    Object listKriteriaNorm[][];
    public int rowAlt;

    /**
     * Creates new form HitungAlternatif
     * @param listKriteria
     */
    public HitungAlternatif(Object listKriteria[][] , int rowAlt1) {
        this.listKriteria = listKriteria;
        this.listKriteriaNorm = listKriteria;
        this.rowAlt = rowAlt1;
        double totalValue = 0;
        for (int i = 0; i < listKriteria.length; i++) {
            totalValue += Double.parseDouble(String.valueOf(listKriteria[i][1]));
        }
        for (int i = 0; i < listKriteria.length; i++) {
            this.listKriteriaNorm[i][1] = Double.parseDouble(String.valueOf(listKriteria[i][1])) / totalValue;
        }
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tb_alternatif = new javax.swing.JTable();
        btn_hapus = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_alternatif.setColumnSelectionAllowed(true);
        tb_alternatif.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tb_alternatifPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tb_alternatif);
        tb_alternatif.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah Alternatif");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hitung.setText("Hitung Rangking");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus)
                .addGap(57, 57, 57)
                .addComponent(btn_hitung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void tb_alternatif(Object obj[][]){
        Object columns [] =new String[(obj.length)+1];
        String data [][] = new String[rowAlt][(obj.length)+1];
        for(int i = 0; i < obj.length;i++){
            for(int j = 0; j<2;j++){
                if(j == 0){
                    columns[0] = "Nama Alternatif";
                    columns[i+1] = obj[i][0];
                }
            }
        }
       DefaultTableModel model = new DefaultTableModel(data,columns);
       tb_alternatif.setModel(model);
    }
    private void tb_alternatifPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tb_alternatifPropertyChange
        
    }//GEN-LAST:event_tb_alternatifPropertyChange

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if (tb_alternatif.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) tb_alternatif.getModel();
            model.removeRow(tb_alternatif.getSelectedRow());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        DefaultTableModel model = (DefaultTableModel) tb_alternatif.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        DefaultTableModel model = (DefaultTableModel) tb_alternatif.getModel();
        if (model.getRowCount() > 0) {
            Object alternatif[][] = new Object[model.getRowCount()][model.getColumnCount()];
            Double minmax[][] = new Double[2][model.getColumnCount()];
            for (int i = 0; i < 2; i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    minmax[i][j] = 0.0;
                }
            }
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    alternatif[i][j] = model.getValueAt(i, j);
                    if (j != 0) {
                        if (minmax[0][j] < Double.parseDouble(String.valueOf(alternatif[i][j]))) {
                            minmax[0][j] = Double.parseDouble(String.valueOf(alternatif[i][j]));
                        }
                        if (i == 0) {
                            minmax[1][j] = Double.parseDouble(String.valueOf(alternatif[i][j]));
                        } else {
                            if (minmax[1][j] > Double.parseDouble(String.valueOf(alternatif[i][j]))) {
                                minmax[1][j] = Double.parseDouble(String.valueOf(alternatif[i][j]));
                            }
                        }
                    }
                }
            }
            Object utilityValue[][] = new Object[model.getRowCount()][model.getColumnCount()];
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    if (j != 0) {
                        utilityValue[i][j] = (Double.parseDouble(String.valueOf(alternatif[i][j])) - minmax[1][j]) / (minmax[0][j] - minmax[1][j]);
                    } else {
                        utilityValue[i][j] = model.getValueAt(i, j);
                    }
                }
            }
            for (int i = 0; i < minmax.length; i++) {
                for (int j = 0; j < minmax[0].length; j++) {
                    System.out.print(minmax[i][j] + " | ");
                }
                System.out.println();
            }
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    System.out.print(utilityValue[i][j] + " | ");
                }
                System.out.println();
            }

        }
    }//GEN-LAST:event_btn_hitungActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_alternatif;
    // End of variables declaration//GEN-END:variables
}
